/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package BO;

/**
 *
 * @author renel
 */
public class Strings {
    public static String url = "jdbc:ucanaccess://C:\\Users\\Caden\\Downloads\\db.accdb";
    public static String driver = "net.ucanaccess.jdbc.UcanaccessDriver";
    //jsp strings
    public static String footer = "               <br><br>\n"
            + "\n"
            + "<footer class=\"page-footer page-footer-default\">\n"
            + "	<div class=\"content\" >\n"
            + "		<section class=\"location\" style=\"margin: 0;\">\n"
            + "			<div class=\"address\">\n"
            + "				<h4 class=\"name\" itemprop=\"name\">The Hair Salon (THS)</h4>\n"
            + "				<div class=\"street\">123 Main Street</div>\n"
            + "                <div class=\"street2\">Suite 108</div>\n"
            + "                <span class=\"city\">Kennesaw,</span>\n"
            + "                <span class=\"state\">GA</span>\n"
            + "                <span class=\"zip\">30152</span>\n"
            + "			</div>\n"
            + "		</section>"
            + "<section class=\"contact-info\" style=\"margin: 0;\">\n"
            + "				<h4>Contact Us</h4>\n"
            + "					<div class=\"practice\">\n"
            + "						<div class=\"footer-pc-text\">E-mail - <a href=\"mailto:info@thehairsalon.com\">info@thehairsalon.com</a></div>\n"
            + "					</div>\n"
            + "                <h4 class=\"tel\" itemprop=\"telephone\">Phone - <a href=\"tel:+1-123-456-7890\">123-456-7890</a></h4>\n"
            + "		</section>\n"
            + "		\n"
            + "		<section class=\"hours\">\n"
            + "				<h4>Salon Hours:</h4>\n"
            + "					<center>\n"
            + "					<div class=\"days\">\n"
            + "						<div class=\"day\" itemprop=\"openingHoursSpecification\" itemscope=\"\" itemtype=\"http://schema.org/OpeningHoursSpecification\" data-day=\"1\">\n"
            + "							<link itemprop=\"dayOfWeek\" href=\"http://schema.org/Monday\">\n"
            + "							<span class=\"label\" title=\"Monday\">Mon</span>\n"
            + "							<span class=\"time\">\n"
            + "								<time class=\"start\" itemprop=\"opens\" content=\"09:00:00\">9:00 AM</time>\n"
            + "								<span class=\"sep\">–</span>\n"
            + "								<time class=\"end\" itemprop=\"closes\" content=\"18:00:00\">6:00 PM</time>\n"
            + "							</span>\n"
            + "						</div>\n"
            + "						\n"
            + "						<div class=\"day\" itemprop=\"openingHoursSpecification\" itemscope=\"\" itemtype=\"http://schema.org/OpeningHoursSpecification\" data-day=\"2\">\n"
            + "							<link itemprop=\"dayOfWeek\" href=\"http://schema.org/Tuesday\">\n"
            + "							<span class=\"label\" title=\"Tuesday\">Tue</span>\n"
            + "							<span class=\"time\">\n"
            + "								<time class=\"start\" itemprop=\"opens\" content=\"09:00:00\">9:00 AM</time>\n"
            + "								<span class=\"sep\">–</span>\n"
            + "								<time class=\"end\" itemprop=\"closes\" content=\"18:00:00\">6:00 PM</time>\n"
            + "							</span>\n"
            + "						</div>\n"
            + "						\n"
            + "						<div class=\"day\" itemprop=\"openingHoursSpecification\" itemscope=\"\" itemtype=\"http://schema.org/OpeningHoursSpecification\" data-day=\"3\">\n"
            + "							<link itemprop=\"dayOfWeek\" href=\"http://schema.org/Wednesday\">\n"
            + "							<span class=\"label\" title=\"Wednesday\">Wed</span>\n"
            + "							<span class=\"time\">\n"
            + "								<time class=\"start\" itemprop=\"opens\" content=\"09:00:00\">9:00 AM</time>\n"
            + "								<span class=\"sep\">–</span>\n"
            + "								<time class=\"end\" itemprop=\"closes\" content=\"18:00:00\">6:00 PM</time>\n"
            + "							</span>\n"
            + "						</div>\n"
            + "						\n"
            + "						<div class=\"day\" itemprop=\"openingHoursSpecification\" itemscope=\"\" itemtype=\"http://schema.org/OpeningHoursSpecification\" data-day=\"4\">\n"
            + "							<link itemprop=\"dayOfWeek\" href=\"http://schema.org/Thursday\">\n"
            + "							<span class=\"label\" title=\"Thursday\">Thu</span>\n"
            + "							<span class=\"time\">\n"
            + "								<time class=\"start\" itemprop=\"opens\" content=\"09:00:00\">9:00 AM</time>\n"
            + "								<span class=\"sep\">–</span>\n"
            + "								<time class=\"end\" itemprop=\"closes\" content=\"18:00:00\">6:00 PM</time>\n"
            + "							</span>\n"
            + "						</div>\n"
            + "						\n"
            + "						<div class=\"day\" itemprop=\"openingHoursSpecification\" itemscope=\"\" itemtype=\"http://schema.org/OpeningHoursSpecification\" data-day=\"5\">\n"
            + "							<link itemprop=\"dayOfWeek\" href=\"http://schema.org/Friday\">\n"
            + "							<span class=\"label\" title=\"Friday\">Fri</span>\n"
            + "							<span class=\"time\">\n"
            + "								<time class=\"start\" itemprop=\"opens\" content=\"09:00:00\">9:00 AM</time>\n"
            + "								<span class=\"sep\">–</span>\n"
            + "								<time class=\"end\" itemprop=\"closes\" content=\"18:00:00\">6:00 PM</time>\n"
            + "							</span>\n"
            + "						</div>\n"
            + "						\n"
            + "						<div class=\"day\" itemprop=\"openingHoursSpecification\" itemscope=\"\" itemtype=\"http://schema.org/OpeningHoursSpecification\" data-day=\"6\">\n"
            + "							<link itemprop=\"dayOfWeek\" href=\"http://schema.org/Friday\">\n"
            + "							<span class=\"label\" title=\"Saturday\">Sat</span>\n"
            + "							<span class=\"time\">\n"
            + "								<time class=\"start\" itemprop=\"opens\" content=\"10:00:00\">10:00 AM</time>\n"
            + "								<span class=\"sep\">–</span>\n"
            + "								<time class=\"end\" itemprop=\"closes\" content=\"18:00:00\">6:00 PM</time>\n"
            + "							</span>\n"
            + "						</div>\n"
            + "						\n"
            + "						<div class=\"day\" itemprop=\"openingHoursSpecification\" itemscope=\"\" itemtype=\"http://schema.org/OpeningHoursSpecification\" data-day=\"7\">\n"
            + "							<link itemprop=\"dayOfWeek\" href=\"http://schema.org/Friday\">\n"
            + "							<span class=\"label\" title=\"Sunday\" style=\"color:red;\">Sun</span>\n"
            + "							<span class=\"time\">\n"
            + "								<time class=\"start\" itemprop=\"opens\" content=\"10:00:00\">10:00 AM</time>\n"
            + "								<span class=\"sep\">–</span>\n"
            + "								<time class=\"end\" itemprop=\"closes\" content=\"18:00:00\">6:00 PM</time>\n"
            + "							</span>\n"
            + "						</div>\n"
            + "					</div>\n"
            + "					</center>\n"
            + "		<br>\n"
            + "		<div class=\"fade_rule\"></div>\n"
            + "		<br>\n"
            + "					\n"
            + "		</section>"
            + "		<section class=\"social\" style=\"margin: 0;\">\n"
            + "			<h4>Social Media</h4>\n"
            + "			<ul class=\"social-icons\">\n"
            + "				<li><a href=\"\"> <img src=\"https://media.discordapp.net/attachments/804523300302618646/821091772071149568/facebook.JPG\" height=\"35\" width=\"40\" style=\"border-radius: 13%;\"></img></a></li>\n"
            + "				<li><a href=\"\"> <img src=\"https://cdn.discordapp.com/attachments/804523300302618646/821091849678749706/twitter.png\" height=\"45\" width=\"75\" style=\"border-radius: 8%;\"></img></a></li>\n"
            + "				<li><a href=\"\"> <img src=\"https://upload.wikimedia.org/wikipedia/commons/thumb/e/e7/Instagram_logo_2016.svg/768px-Instagram_logo_2016.svg.png\" height=\"35\" width=\"40\" style=\"border-radius: 13%;\"></img></a></li>\n"
            + "			</ul>\n"
            + "		</section>\n"
            + "\n"
            + "	</div>\n"
            + "</footer>";
}